const tag_length = 10;

var tag = 
{
	MEL: 	0x0001,
	RCK: 	0x0002,
	HVY: 	0x0004,
	MLD:	0x0008,
	EXP: 	0x0010,
	AMB: 	0x0020,
	FNK:	0x0040,
	TCH:	0x0080,
	BSY: 	0x0100,
	JAM: 	0x0200,
}

var pikes =
[
/* 001 */	{ album_id: 3461343610, tags: 	(tag.RCK | tag.MLD									) },
/* 002 */	{ album_id: 3251674158, tags: 	(tag.RCK | tag.BSY | tag.EXP						) },
/* 003 */	{ album_id: 671315937,	tags: 	(tag.RCK | tag.MLD									) },
/* 004 */	{ album_id: 1506033273,	tags: 	(tag.EXP | tag.TCH									) },
/* 005 */	{ album_id: 2888087378,	tags: 	(tag.MEL | tag.RCK | tag.JAM						) },
/* 006 */	{ album_id: 179798548,	tags: 	(tag.RCK | tag.EXP | tag.TCH						) },
/* 007 */	{ album_id: 3729053290,	tags:	(tag.RCK | tag.HVY | tag.EXP | tag.MLD				) },
/* 008 */	{ album_id: 3488681779,	tags:	(tag.MEL | tag.HVY | tag.MLD | tag.RCK				) },
/* 009 */	{ album_id: 0,			tags:	(tag.MEL | tag.RCK | tag.BSY | tag.MLD				) },
/* 010 */	{ album_id: 0,			tags:	(tag.MEL | tag.RCK | tag.HVY | tag.MLD				) },

/* 011 */	{ album_id: 1707332795, tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 012 */	{ album_id: 2185679906, tags: 	(tag.RCK | tag.EXP | tag.MLD						) },
/* 013 */	{ album_id: 0, 			tags: 	(tag.MEL | tag.AMB | tag.MLD						) },
/* 014 */	{ album_id: 846783511, 	tags: 	(tag.HVY | tag.BSY | tag.TCH | tag.EXP				) },
/* 015 */	{ album_id: 69037843, 	tags: 	(tag.MEL | tag.MLD									) },
/* 016 */	{ album_id: 345001496, 	tags: 	(tag.HVY											) },
/* 017 */	{ album_id: 2258281250, tags: 	(tag.MEL | tag.MLD									) },
/* 018 */	{ album_id: 554373173, 	tags: 	(tag.MEL | tag.MLD									) },
/* 019 */	{ album_id: 973623100, 	tags: 	(tag.HVY | tag.EXP									) },
/* 020 */	{ album_id: 133475318, 	tags: 	(tag.HVY | tag.EXP									) },

/* 021 */	{ album_id: 2624189332, tags: 	(tag.RCK | tag.EXP									) },
/* 022 */	{ album_id: 3340299435, tags: 	(tag.RCK | tag.HVY | tag.EXP						) },
/* 023 */	{ album_id: 4005772730, tags: 	(tag.RCK | tag.HVY | tag.AMB						) },
/* 024 */	{ album_id: 910635251, 	tags: 	(tag.HVY											) },
/* 025 */	{ album_id: 3380001260, tags: 	(tag.HVY											) },
/* 026 */	{ album_id: 1093248279, tags: 	(tag.HVY | tag.JAM									) },
/* 027 */	{ album_id: 3760330922, tags: 	(tag.HVY | tag.BSY | tag.EXP | tag.AMB				) },
/* 028 */	{ album_id: 2667143486, tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 029 */	{ album_id: 1784398253, tags: 	(tag.EXP | tag.TCH									) },
/* 030 */	{ album_id: 2404702447, tags: 	(tag.HVY											) },

/* 031 */	{ album_id: 3245813562, tags: 	(tag.MEL | tag.MLD									) },
/* 032 */	{ album_id: 592479530,  tags: 	(tag.MEL | tag.MLD									) },
/* 033 */	{ album_id: 411022782,  tags: 	(tag.AMB | tag.EXP									) },
/* 034 */	{ album_id: 0, 			tags: 	(tag.AMB | tag.EXP									) },
/* 035 */	{ album_id: 86866986, 	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 036 */	{ album_id: 2406470738, tags: 	(tag.MEL | tag.HVY									) },
/* 037 */	{ album_id: 300237056, 	tags: 	(tag.RCK | tag.HVY									) },
/* 038 */	{ album_id: 2165829246, tags: 	(tag.RCK | tag.HVY									) },
/* 039 */	{ album_id: 3246051786, tags: 	(tag.RCK | tag.HVY | tag.JAM						) },
/* 040 */	{ album_id: 2260956499, tags: 	(tag.MEL | tag.RCK									) },

/* 041 */	{ album_id: 1567814700, tags: 	(tag.MEL | tag.MLD									) },
/* 042 */	{ album_id: 1384368277, tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 043 */	{ album_id: 0, 			tags: 	(tag.MEL | tag.MLD									) },
/* 044 */	{ album_id: 4023751924, tags: 	(tag.HVY | tag.EXP									) },
/* 045 */	{ album_id: 653439869, 	tags: 	(tag.RCK | tag.HVY | tag.JAM						) },
/* 046 */	{ album_id: 738124806, 	tags: 	(tag.MEL | tag.MLD									) },
/* 047 */	{ album_id: 4262168305, tags: 	(tag.HVY | tag.TCH									) },
/* 048 */	{ album_id: 2388789682, tags: 	(tag.RCK | tag.FNK									) },
/* 049 */	{ album_id: 3114028999, tags: 	(tag.MEL | tag.MLD									) },
/* 050 */	{ album_id: 540940851, 	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },

/* 051 */	{ album_id: 3714251669, tags: 	(tag.RCK | tag.JAM | tag.MLD						) },
/* 052 */	{ album_id: 2173054383, tags: 	(tag.RCK | tag.EXP | tag.FNK						) },
/* 053 */	{ album_id: 2442159329, tags: 	(tag.MEL | tag.RCK | tag.BSY | tag.MLD				) },
/* 054 */	{ album_id: 3209527163, tags: 	(tag.BSY | tag.FNK | tag.MLD						) },
/* 055 */	{ album_id: 576866303, 	tags: 	(tag.HVY | tag.TCH									) },
/* 056 */	{ album_id: 3788103254, tags: 	(tag.MEL | tag.BSY									) },
/* 057 */	{ album_id: 836619877, 	tags: 	(tag.BSY | tag.EXP									) },
/* 058 */	{ album_id: 2161247157, tags: 	(tag.RCK | tag.BSY | tag.FNK						) },
/* 059 */	{ album_id: 2592193252, tags: 	(tag.HVY | tag.EXP									) },
/* 060 */	{ album_id: 0, 			tags: 	(tag.MEL | tag.MLD									) },

/* 061 */	{ album_id: 3556284119, tags: 	(tag.HVY | tag.EXP | tag.MEL | tag.AMB				) },
/* 062 */	{ album_id: 33105586, 	tags: 	(tag.RCK | tag.EXP									) },
/* 063 */	{ album_id: 3855412264, tags: 	(tag.AMB | tag.EXP									) },
/* 064 */	{ album_id: 619629729, 	tags: 	(tag.RCK | tag.HVY									) },
/* 065 */	{ album_id: 4097328708, tags: 	(tag.RCK | tag.JAM | tag.MLD						) },
/* 066 */	{ album_id: 626340121, 	tags: 	(tag.RCK | tag.JAM | tag.MLD						) },
/* 067 */	{ album_id: 684721453, 	tags: 	(tag.HVY | tag.EXP | tag.AMB						) },
/* 068 */	{ album_id: 2136139916, tags: 	(tag.HVY | tag.EXP									) },
/* 069 */	{ album_id: 3217707637, tags: 	(tag.RCK | tag.BSY | tag.EXP | tag.FNK				) },
/* 070 */	{ album_id: 3276482754, tags: 	(tag.RCK | tag.BSY | tag.FNK						) },

/* 071 */	{ album_id: 0, 			tags: 	(tag.RCK | tag.JAM									) },
/* 072 */	{ album_id: 3377772020, tags: 	(tag.MEL | tag.MLD									) },
/* 073 */	{ album_id: 2422392380, tags: 	(tag.RCK | tag.JAM | tag.MLD						) },
/* 074 */	{ album_id: 845841686,  tags: 	(tag.RCK | tag.BSY | tag.FNK						) },
/* 075 */	{ album_id: 1132789037, tags: 	(tag.HVY | tag.MEL | tag.EXP | tag.AMB				) },
/* 076 */	{ album_id: 3998872307, tags: 	(tag.RCK | tag.BSY | tag.FNK						) },
/* 077 */	{ album_id: 97343917, 	tags: 	(tag.HVY											) },
/* 078 */	{ album_id: 0, 			tags: 	(tag.MEL | tag.MLD									) },
/* 079 */	{ album_id: 2780720019, tags: 	(tag.HVY | tag.EXP									) },
/* 080 */	{ album_id: 4116342344, tags: 	(tag.RCK | tag.BSY | tag.EXP						) },

/* 081 */	{ album_id: 788390560, 	tags: 	(tag.EXP											) },
/* 082 */	{ album_id: 1514784074, tags: 	(tag.HVY											) },
/* 083 */	{ album_id: 2760207119, tags: 	(tag.RCK | tag.EXP									) },
/* 084 */	{ album_id: 1276437152, tags: 	(tag.HVY | tag.EXP									) },
/* 085 */	{ album_id: 1907804326, tags: 	(tag.RCK											) },
/* 086 */	{ album_id: 939057559, 	tags: 	(tag.RCK | tag.MEL									) },
/* 087 */	{ album_id: 269878640, 	tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 088 */	{ album_id: 1252137600, tags: 	(tag.MEL | tag.EXP | tag.MLD | tag.RCK				) },
/* 089 */	{ album_id: 3690399548, tags: 	(tag.RCK | tag.AMB									) },
/* 090 */	{ album_id: 484058747,	tags: 	(tag.RCK | tag.JAM | tag.MLD						) },

/* 091 */	{ album_id: 1629365297,	tags: 	(tag.RCK | tag.TCH | tag.FNK						) },
/* 092 */	{ album_id: 1404712775,	tags: 	(tag.RCK | tag.EXP									) },
/* 093 */	{ album_id: 2665512438,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },
/* 094 */	{ album_id: 1492355884,	tags: 	(tag.RCK | tag.FNK | tag.MLD						) },
/* 095 */	{ album_id: 3513108982,	tags: 	(tag.RCK | tag.JAM									) },
/* 096 */	{ album_id: 1857640172,	tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 097 */	{ album_id: 3930981693,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 098 */	{ album_id: 624042829,	tags: 	(tag.BSY | tag.EXP									) },
/* 099 */	{ album_id: 3946249974,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },
/* 100 */	{ album_id: 1490366463,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },

/* 101 */	{ album_id: 1338508163,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 102 */	{ album_id: 1201722285,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },
/* 103 */	{ album_id: 3313832813,	tags: 	(tag.RCK | tag.FNK									) },
/* 104 */	{ album_id: 2965511149,	tags: 	(tag.RCK | tag.JAM									) },
/* 105 */	{ album_id: 354578486,	tags: 	(tag.RCK | tag.JAM									) },
/* 106 */	{ album_id: 591995885,	tags: 	(tag.RCK | tag.EXP									) },
/* 107 */	{ album_id: 340881623,	tags: 	(tag.RCK | tag.TCH									) },
/* 108 */	{ album_id: 2617382846,	tags: 	(tag.RCK | tag.HVY | tag.TCH						) },
/* 109 */	{ album_id: 1841034779,	tags: 	(tag.MEL | tag.MLD									) },
/* 110 */	{ album_id: 2624965199,	tags: 	(tag.RCK | tag.TCH | tag.MLD						) },

/* 111 */	{ album_id: 2869817516,	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 112 */	{ album_id: 268848590,	tags: 	(tag.BSY | tag.EXP | tag.TCH						) },
/* 113 */	{ album_id: 2272122178,	tags: 	(tag.RCK | tag.EXP | tag.TCH						) },
/* 114 */	{ album_id: 71302737,	tags: 	(tag.HVY											) },
/* 115 */	{ album_id: 738244821,	tags: 	(tag.EXP											) },
/* 116 */	{ album_id: 1879780780,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 117 */	{ album_id: 3106964393,	tags: 	(tag.BSY											) },
/* 118 */	{ album_id: 752427423,	tags: 	(tag.RCK | tag.HVY | tag.TCH						) },
/* 119 */	{ album_id: 1831698057,	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 120 */	{ album_id: 1608530496,	tags: 	(tag.RCK | tag.EXP | tag.BSY						) },

/* 121 */	{ album_id: 2828871365,	tags: 	(tag.RCK | tag.JAM									) },
/* 122 */	{ album_id: 2549727678,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },
/* 123 */	{ album_id: 1168988862,	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 124 */	{ album_id: 3569961347,	tags: 	(tag.EXP											) },
/* 125 */	{ album_id: 4240446951,	tags: 	(tag.RCK | tag.MLD									) },
/* 126 */	{ album_id: 831084116,	tags: 	(tag.RCK | tag.HVY | tag.BSY						) },
/* 127 */	{ album_id: 742598399,	tags: 	(tag.MEL | tag.RCK									) },
/* 128 */	{ album_id: 1514672809,	tags: 	(tag.MEL | tag.MLD									) },
/* 129 */	{ album_id: 805612302,	tags: 	(tag.MEL | tag.RCK									) },
/* 130 */	{ album_id: 2633660071,	tags: 	(tag.HVY | tag.AMB									) },

/* 131 */	{ album_id: 3554232639,	tags: 	(tag.RCK | tag.AMB									) },
/* 132 */	{ album_id: 1465199139,	tags: 	(tag.RCK | tag.HVY									) },
/* 133 */	{ album_id: 1790529414,	tags: 	(tag.HVY | tag.AMB									) },
/* 134 */	{ album_id: 2001981877,	tags: 	(tag.EXP | tag.AMB									) },
/* 135 */	{ album_id: 1711486006,	tags: 	(tag.EXP | tag.AMB									) },
/* 136 */	{ album_id: 705489165,	tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 137 */	{ album_id: 1964024887,	tags: 	(tag.HVY											) },
/* 138 */	{ album_id: 1058745253,	tags: 	(tag.RCK | tag.HVY | tag.EXP | tag.TCH | tag.MLD	) },
/* 139 */	{ album_id: 1409758277,	tags: 	(tag.RCK | tag.JAM									) },
/* 140 */	{ album_id: 1525089418,	tags: 	(tag.RCK | tag.EXP | tag.JAM						) },

/* 141 */	{ album_id: 2609601653,	tags: 	(tag.BSY | tag.EXP | tag.FNK						) },
/* 142 */	{ album_id: 3218010786,	tags: 	(tag.RCK | tag.EXP									) },
/* 143 */	{ album_id: 205411446,	tags: 	(tag.RCK | tag.EXP | tag.MLD						) },
/* 144 */	{ album_id: 2372443440,	tags: 	(tag.RCK | tag.BSY | tag.TCH						) },
/* 145 */	{ album_id: 718693301,	tags: 	(tag.RCK | tag.BSY | tag.FNK						) },
/* 146 */	{ album_id: 1389427519,	tags: 	(tag.RCK | tag.EXP									) },
/* 147 */	{ album_id: 2784727515,	tags: 	(tag.RCK | tag.BSY | tag.FNK						) },
/* 148 */	{ album_id: 1707127791,	tags: 	(tag.MEL | tag.MLD									) },
/* 149 */	{ album_id: 899471657,	tags: 	(tag.RCK | tag.HVY | tag.TCH | tag.MLD				) },
/* 150 */	{ album_id: 921265789,	tags: 	(tag.MEL | tag.MLD									) },

/* 151 */	{ album_id: 1870486126,	tags: 	(tag.RCK | tag.EXP | tag.MLD						) },
/* 152 */	{ album_id: 3782040561,	tags: 	(tag.RCK | tag.EXP | tag.TCH						) },
/* 153 */	{ album_id: 197494208,	tags: 	(tag.RCK | tag.TCH									) },
/* 154 */	{ album_id: 3236763919,	tags: 	(tag.MEL | tag.RCK | tag.HVY						) },
/* 155 */	{ album_id: 4073274924,	tags: 	(tag.RCK | tag.HVY									) },
/* 156 */	{ album_id: 2741020956,	tags: 	(tag.MEL | tag.RCK | tag.HVY | tag.BSY | tag.MLD	) },
/* 157 */	{ album_id: 2044907017,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },
/* 158 */	{ album_id: 3200012919,	tags: 	(tag.HVY											) },
/* 159 */	{ album_id: 1361472948,	tags: 	(tag.HVY | tag.EXP | tag.AMB | tag.TCH				) },
/* 160 */	{ album_id: 1900557132,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },

/* 161 */	{ album_id: 0,			tags: 	(tag.EXP | tag.AMB									) },
/* 162 */	{ album_id: 421546742,	tags: 	(tag.MEL | tag.RCK | tag.HVY | tag.MLD				) },
/* 163 */	{ album_id: 2175031907,	tags: 	(tag.MEL | tag.MLD									) },
/* 164 */	{ album_id: 3981274236,	tags: 	(tag.RCK | tag.HVY									) },
/* 165 */	{ album_id: 3817769749,	tags: 	(tag.RCK | tag.BSY | tag.EXP | tag.TCH				) },
/* 166 */	{ album_id: 245092693,	tags: 	(tag.MEL | tag.RCK | tag.BSY | tag.MLD				) },
/* 167 */	{ album_id: 3771004123,	tags: 	(tag.MEL | tag.RCK | tag.JAM						) },
/* 168 */	{ album_id: 2380462831,	tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 169 */	{ album_id: 958589763,	tags: 	(tag.BSY | tag.FNK | tag.MLD						) },
/* 170 */	{ album_id: 4281088144,	tags: 	(tag.MEL | tag.HVY | tag.MLD						) },

/* 171 */	{ album_id: 2558198586,	tags: 	(tag.HVY | tag.EXP									) },
/* 172 */	{ album_id: 906344908,	tags: 	(tag.HVY											) },
/* 173 */	{ album_id: 2867569821,	tags: 	(tag.HVY | tag.EXP									) },
/* 174 */	{ album_id: 575494761,	tags: 	(tag.HVY | tag.TCH									) },
/* 175 */	{ album_id: 369687226,	tags: 	(tag.MEL | tag.AMB									) },
/* 176 */	{ album_id: 3986502857,	tags: 	(tag.AMB | tag.EXP									) },
/* 177 */	{ album_id: 904535379,	tags: 	(tag.AMB | tag.EXP									) },
/* 178 */	{ album_id: 4162833234,	tags: 	(tag.HVY | tag.TCH									) },
/* 179 */	{ album_id: 3331276578,	tags: 	(tag.AMB | tag.EXP									) },
/* 180 */	{ album_id: 1635746769,	tags: 	(tag.AMB | tag.EXP									) },

/* 181 */	{ album_id: 1454026805,	tags: 	(tag.AMB | tag.EXP									) },
/* 182 */	{ album_id: 3626305521,	tags: 	(tag.AMB | tag.EXP									) },
/* 183 */	{ album_id: 2205526562,	tags: 	(tag.AMB | tag.EXP									) },
/* 184 */	{ album_id: 1499013645,	tags: 	(tag.AMB | tag.EXP									) },
/* 185 */	{ album_id: 650543463,	tags: 	(tag.AMB | tag.EXP									) },
/* 186 */	{ album_id: 829111656,	tags: 	(tag.AMB | tag.EXP									) },
/* 187 */	{ album_id: 537812349,	tags: 	(tag.AMB | tag.EXP									) },
/* 188 */	{ album_id: 1474658778,	tags: 	(tag.AMB | tag.EXP									) },
/* 189 */	{ album_id: 2819276341,	tags: 	(tag.AMB | tag.EXP									) },
/* 190 */	{ album_id: 3149080954,	tags: 	(tag.AMB | tag.EXP									) },

/* 191 */	{ album_id: 5031917,	tags: 	(tag.AMB | tag.EXP									) },
/* 192 */	{ album_id: 3805634148,	tags: 	(tag.AMB | tag.EXP									) },
/* 193 */	{ album_id: 89898231,	tags: 	(tag.AMB | tag.EXP									) },
/* 194 */	{ album_id: 1214401972,	tags: 	(tag.AMB | tag.EXP									) },
/* 195 */	{ album_id: 355230612,	tags: 	(tag.AMB | tag.EXP									) },
/* 196 */	{ album_id: 3916469824,	tags: 	(tag.AMB | tag.EXP									) },
/* 197 */	{ album_id: 186845007,	tags: 	(tag.AMB | tag.EXP									) },
/* 198 */	{ album_id: 959161764,	tags: 	(tag.AMB | tag.EXP									) },
/* 199 */	{ album_id: 450431876,	tags: 	(tag.AMB | tag.EXP | tag.RCK						) },
/* 200 */	{ album_id: 703323594,	tags: 	(tag.AMB | tag.EXP									) },

/* 201 */	{ album_id: 4017237275,	tags: 	(tag.AMB | tag.EXP									) },
/* 202 */	{ album_id: 784075539,	tags: 	(tag.AMB | tag.EXP									) },
/* 203 */	{ album_id: 3797412461,	tags: 	(tag.AMB | tag.EXP									) },
/* 204 */	{ album_id: 1669210734,	tags: 	(tag.AMB | tag.EXP									) },
/* 205 */	{ album_id: 1606474884,	tags: 	(tag.AMB | tag.EXP									) },
/* 206 */	{ album_id: 212060769,	tags: 	(tag.AMB | tag.EXP | tag.TCH						) },
/* 207 */	{ album_id: 2044814498,	tags: 	(tag.AMB | tag.EXP									) },
/* 208 */	{ album_id: 0,			tags: 	(tag.MEL | tag.AMB									) },
/* 209 */	{ album_id: 1730079496,	tags: 	(tag.MEL | tag.MLD									) },
/* 210 */	{ album_id: 3682426965,	tags: 	(tag.RCK | tag.JAM | tag.HVY | tag.TCH				) },

/* 211 */	{ album_id: 760782589,	tags: 	(tag.RCK | tag.MLD									) },
/* 212 */	{ album_id: 357384462,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 213 */	{ album_id: 289531930,	tags: 	(tag.RCK | tag.JAM									) },
/* 214 */	{ album_id: 2143564273,	tags: 	(tag.MEL											) },
/* 215 */	{ album_id: 35741417,	tags: 	(tag.RCK | tag.HVY | tag.TCH | tag.MLD				) },
/* 216 */	{ album_id: 1674296600,	tags: 	(tag.RCK | tag.MLD									) },
/* 217 */	{ album_id: 1394379487,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 218 */	{ album_id: 2239147214,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 219 */	{ album_id: 316002470,	tags: 	(tag.MEL | tag.RCK | tag.HVY | tag.MLD				) },
/* 220 */	{ album_id: 616300190,	tags: 	(tag.MEL | tag.HVY | tag.TCH | tag.MLD				) },

/* 221 */	{ album_id: 218220045,	tags: 	(tag.MEL | tag.MLD									) },
/* 222 */	{ album_id: 4226370174,	tags: 	(tag.HVY | tag.TCH									) },
/* 223 */	{ album_id: 3456875009,	tags: 	(tag.MEL											) },
/* 224 */	{ album_id: 2734879202,	tags: 	(tag.RCK | tag.MEL | tag.MLD						) },
/* 225 */	{ album_id: 265596910,	tags: 	(tag.RCK											) },
/* 226 */	{ album_id: 3459766685,	tags: 	(tag.RCK | tag.JAM | tag.MLD						) },
/* 227 */	{ album_id: 1893018082,	tags: 	(tag.MEL | tag.HVY									) },
/* 228 */	{ album_id: 1370784978,	tags: 	(tag.HVY | tag.TCH									) },
/* 229 */	{ album_id: 1369708131,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 230 */	{ album_id: 3470999186,	tags: 	(tag.RCK | tag.JAM | tag.HVY						) },

/* 231 */	{ album_id: 4284162107,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 232 */	{ album_id: 2909262998,	tags: 	(tag.RCK | tag.HVY | tag.JAM | tag.MLD				) },
/* 233 */	{ album_id: 1344891878,	tags: 	(tag.RCK | tag.HVY | tag.EXP | tag.MLD				) },
/* 234 */	{ album_id: 363382626,	tags: 	(tag.RCK | tag.EXP | tag.JAM | tag.TCH				) },
/* 235 */	{ album_id: 433620030,	tags: 	(tag.RCK | tag.MLD									) },
/* 236 */	{ album_id: 1551870852,	tags: 	(tag.RCK | tag.HVY | tag.EXP						) },
/* 237 */	{ album_id: 1000891439,	tags: 	(tag.RCK											) },
/* 238 */	{ album_id: 5397140,	tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 239 */	{ album_id: 3476797241,	tags: 	(tag.MEL | tag.RCK | tag.FNK | tag.MLD				) },
/* 240 */	{ album_id: 2858084261,	tags: 	(tag.RCK | tag.HVY									) },

/* 241 */	{ album_id: 1291198858,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 242 */	{ album_id: 2934844995,	tags: 	(tag.HVY | tag.TCH									) },
/* 243 */	{ album_id: 2434785430,	tags: 	(tag.RCK | tag.HVY | tag.EXP | tag.TCH				) },
/* 244 */	{ album_id: 124433561,	tags: 	(tag.RCK | tag.HVY | tag.EXP						) },
/* 245 */	{ album_id: 4015772487,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 246 */	{ album_id: 3036886421,	tags: 	(tag.RCK | tag.HVY | tag.JAM						) },
/* 247 */	{ album_id: 798135563,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 248 */	{ album_id: 2047067580,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 249 */	{ album_id: 3484768362,	tags: 	(tag.RCK | tag.HVY									) },
/* 250 */	{ album_id: 3305049446,	tags: 	(tag.HVY | tag.BSY | tag.EXP | tag.TCH				) },

/* 251 */	{ album_id: 2327313959,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 252 */	{ album_id: 910686823,	tags: 	(tag.RCK | tag.MLD									) },
/* 253 */	{ album_id: 30822174,	tags: 	(tag.RCK | tag.TCH | tag.MLD						) },
/* 254 */	{ album_id: 2348647144,	tags: 	(tag.HVY | tag.EXP | tag.TCH						) },
/* 255 */	{ album_id: 925686605,	tags: 	(tag.RCK | tag.HVY | tag.TCH						) },
/* 256 */	{ album_id: 65694138,	tags: 	(tag.RCK | tag.TCH | tag.MLD						) },
/* 257 */	{ album_id: 3281823720,	tags: 	(tag.RCK | tag.MLD									) },
/* 258 */	{ album_id: 2187126134,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 259 */	{ album_id: 2696173338,	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 260 */	{ album_id: 2749899088,	tags: 	(tag.HVY											) },

/* 261 */	{ album_id: 2850546123,	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 262 */	{ album_id: 1842068689,	tags: 	(tag.RCK | tag.TCH									) },
/* 263 */	{ album_id: 2478576641,	tags: 	(tag.RCK | tag.HVY | tag.MLD						) },
/* 264 */	{ album_id: 3900862108,	tags: 	(tag.RCK | tag.MLD									) },
/* 265 */	{ album_id: 1738649259,	tags: 	(tag.RCK | tag.HVY | tag.EXP						) },
/* 266 */	{ album_id: 4272913642,	tags: 	(tag.MEL | tag.RCK | tag.MLD						) },
/* 267 */	{ album_id: 1175225817,	tags: 	(tag.RCK | tag.HVY | tag.EXP | tag.TCH				) },
/* 268 */	{ album_id: 2079882031,	tags: 	(tag.RCK | tag.HVY | tag.JAM | tag.TCH				) },
/* 269 */	{ album_id: 3483164685,	tags: 	(tag.RCK | tag.HVY | tag.TCH						) },
/* 270 */	{ album_id: 3328755506,	tags: 	(tag.MEL | tag.EXP | tag.AMB						) },

/* 271 */	{ album_id: 3731029637,	tags: 	(tag.RCK | tag.MLD									) },
/* 272 */	{ album_id: 2610734609,	tags: 	(tag.MEL | tag.AMB									) },
/* 273 */	{ album_id: 2452309039,	tags: 	(tag.RCK | tag.EXP | tag.TCH						) },
/* 274 */	{ album_id: 1275825909,	tags: 	(tag.RCK | tag.HVY | tag.EXP						) },
/* 275 */	{ album_id: 2037174105,	tags: 	(tag.MEL | tag.RCK | tag.EXP | tag.TCH				) },
]

var pike_descriptions =
[
/* 001 */	"The very first Pike starts off with a bang in the form of hard rock riffing with occassional short, but powerful and memorable guitar solos.",
/* 002 */	"Unstructured songs with occassionally amazing guitar solos and bass-driven riffs.",
/* 003 */	"Many different styles of rock and shred. Also has some chiller songs inbetween and ends with a bit more experimental tunes.",
/* 004 */	"Non-stop shredding, tapping and circuit bending.",
/* 005 */	"Starts off with a mellow rock jam followed by over 20 minutes of fantastic steel guitar soloing.",
/* 006 */	"A continuous track of lots of riffing, wah, shredding, growls, killswitch action, and with little to no breaks.",
/* 007 */	"Hard rock with some heavy riffing and the occassional dubstep-like screeches and growls. Ends with a chill jam.",
/* 008 */	"A mix of hard rock riffs and mellow guitar jams. Final track is an amazingly chill and atmospheric guitar solo.",
/* 009 */	"Many different styles that come on and go, including but not limited to heavy riffs, bluesy solos and bassy jams.",
/* 010 */	"Starts off with fairly heavy riffing, then dwells into a collection of mellow songs followed by a hard rock track. Ends with an atmospheric mellow jam.",

/* 011 */	"Heavy riffs joined by hard rock elements and lengthy guitar solos. Also has some short folk guitar sections.",
/* 012 */	"First half is a big mix of hard rock, wah, and steel guitar. The other half is mostly strange, screechy riffs which ends with spooky ambience.",
/* 013 */	"Beautifully atmospheric with a very sad undertone. Dark places were visited during the recording of this Pike.",
/* 014 */	"Very heavy and chaotic riffing plus shredding accompanied by the occassional juicy bass.",
/* 015 */	"Mostly clean and acoustic guitar tracks. Some are sad and atmospheric while others sound almost poppy. Second track is a short rock song with a very memorable solo.",
/* 016 */	"Exceptionally heavy riffage that will definitely cause whiplash.",
/* 017 */	"Long, relaxing steel guitar jam that ends with a bunch of very short, but varied songs.",
/* 018 */	"Melodic and relaxing acoustic guitar with a lengthy jam at the end.",
/* 019 */	"Very heavy and unstructured. Lots of variety and exceptionally crazy drums.",
/* 020 */	"Slow, downtuned and weird riffs. The last 3 tracks are more structured, but remain heavy.",

/* 021 */	"Rock riffs with very unusual percussion and growly sound samples.",
/* 022 */	"Hard rock mixed with buzzy synths, growls, and strange percussion. Ends with a slow and mellow track.",
/* 023 */	"Heavy riffs from outer space. Comes with spacey sound samples and an amazing outro in the form of a guitar solo.",
/* 024 */	"On-and-off brutal riffing into palm-muted noodling.",
/* 025 */	"Groovily heavy riffs that can only be described as stoner metal.",
/* 026 */	"Starts off with a massive and heavy guitar solo, then slows down to headbanging riffs.",
/* 027 */	"Begins with a bassy jam, then does a complete 180 and throws you into a bizarre dimension with heavy riffs, strange sound samples and Spanish guitar.",
/* 028 */	"Very heavy with lots of growling. The other half includes spooky plucking, a bassy jam, and a crazy shred over a drum track.",
/* 029 */	"Non-stop unstructured shredding, growling and lasers.",
/* 030 */	"Heavy palm-muted chugging and riffing.",

/* 031 */	"An acoustic journey that'll reduce the weight off your shoulders. The mellow jam occassionally has some fast, but gentle shredding.",
/* 032 */	"Three tracks consisting of emotional and acoustic beauty. Final track is a long, mellow jam.",
/* 033 */	"Spooky banjo plucking with background noises reserved for Halloween.",
/* 034 */	"Creepy synth and random sound samples with reverb.",
/* 035 */	"Hard rock melodies and riffs at both slow and fast tempos.",
/* 036 */	"Very heavy riffing encapsulated by emotional and mellow guitar solos.",
/* 037 */	"Heavy riffs one after another. Has a very consistent hard rock theme.",
/* 038 */	"Starts off with a long continuous track consisting of various reoccuring riffs and licks. Ends with a heavy riff-fest.",
/* 039 */	"Kicks off with a heavy, face-melting guitar solo, then slows down to mostly riffing.",
/* 040 */	"The first one-third of this Pike is a collection of beautiful, mellow riffs. Then goes into a long track that builds up heavier and heavier with reoccuring melodies.",

/* 041 */	"First track is fairly fast hybrid-picked on a steel guitar. The rest of this Pike will soothe your soul and put you in a dream-like state with its mellow jams.",
/* 042 */	"On-and-off hard rock riffing into mellow intermissions.",
/* 043 */	"Very emotional and mellow guitar jams. Second track breaks the mold with a fast-paced, fantastic and memorable guitar solo.",
/* 044 */	"Extremely fast-paced riffing with inhuman drums.",
/* 045 */	"Big, amazing guitar solo with tons of shred right off the bat followed by pretty heavy riffing.",
/* 046 */	"This Pike captures a comfy, rainy day with its sound only. Very relaxing and soothing.",
/* 047 */	"Relentlessly heavy riffs with non-stop shredding on top of it.",
/* 048 */	"Rhytmic riffs with heavy distortion.",
/* 049 */	"Emotional masterpiece that will soothe your soul with Western-style, atmospheric melodies and guitar solos.",
/* 050 */	"Slow-paced, relaxing tracks with steel guitar backing tracks and wah lead that will make you go wow.",

/* 051 */	"Hard rock entry track with very memorable melodies followed by an amazingly long guitar jam. Ends with fast-paced hard rock into a fantastic guitar solo.",
/* 052 */	"Very rhythmic and unstructured piece of art with a very varied theme including but not limited to funk, blues, and mellow breaks.",
/* 053 */	"Opens up with quite the groovy improvisation, then throws in more bass and mellowness. The climax is a chill guitar solo with lots of wah.",
/* 054 */	"Three long bassy jams that will definitely make you dance.",
/* 055 */	"Very fast-paced and heavy riffing accompanied by unreal shreddage.",
/* 056 */	"Relaxing bassy backing track with soft, lead steel guitar melodies. Final track kicks up the pace and involves some bass slapping.",
/* 057 */	"Slow bass riffs with strange, distorted guitar lead.",
/* 058 */	"Extremely rhythmic bass-fest with excellent jamming sessions. Get ready to dance.",
/* 059 */	"The Jeopardy theme song from Hell includes crazy shred and very heavily distorted barrages of riffing.",
/* 060 */	"Single track of atmospheric mellow guitar that will relax you to no end.",

/* 061 */	"Heavy riffing that is not from this world. Sometimes breaks into random bass jams. Ends with an atmospheric and relaxing guitar piece.",
/* 062 */	"Strange, unstructured tunes with heavy distortion accompanied by a drum track.",
/* 063 */	"Random guitar plucking and screeching.",
/* 064 */	"Fast-paced hard rock with awesome riffs.",
/* 065 */	"Very emotional hard rock track with a memorable tone that builds up to a long, bittersweet guitar solo that will change your life.",
/* 066 */	"Starts off with a long fast-paced guitar solo and is then followed by slower, jammy rock songs. The Pike then ends with faster and heavier soloing.",
/* 067 */	"Extremely heavy riffing and chugging accompanied by industrial ambience. Ends with beeps and static guitar noise.",
/* 068 */	"Unstructured Pike with heavy riffing, synths, and other strange sound bits.",
/* 069 */	"Bass-heavy Pike with distorted lead guitar playing bizarre melodies.",
/* 070 */	"Rocky riffs with a prominent bass guitar that will make your hips swing left and right.",

/* 071 */	"Single-track Pike with a consistent, slow backing track. Lead guitar is out of this world and something you won't forget any time soon.",
/* 072 */	"Exceptionally beautiful mellow jams with a consistent theme of pleasure and sadness.",
/* 073 */	"Hard rock with many different riffs and melodies. Ends with a long and slow guitar solo.",
/* 074 */	"A lot of rhythmic riffing and noticeable bass guitar.",
/* 075 */	"Starts off heavy and weird, then buckles you up into a very relaxing and haunting ride.",
/* 076 */	"Varied collection of rock tunes and riffs.",
/* 077 */	"Heavy riffing at both slow and fast tempos.",
/* 078 */	"Four tracks that involve mellow, clean sound, with all of them being long and emotional guitar jams.",
/* 079 */	"This Pike has a heavy, muffled, and distorted theme throughout. Heavy riffage ahead.",
/* 080 */	"Very bass-driven, both slap and distorted. Also gets quite heavy.",

/* 081 */	"One long track of a typical carnival theme song mixed with distorted screeching and noise.",
/* 082 */	"Heavy and evil-sounding riffing from start to finish.",
/* 083 */	"Unstructured tracks with strange distorted noises and atmospheric steel guitar intermissions.",
/* 084 */	"Relentlessly heavy with bizarre distorted screeching throughout.",
/* 085 */	"Easy-to-listen rock riffs with a consistent theme.",
/* 086 */	"Rock riffs with a mellow undertone.",
/* 087 */	"Starts off with pure shred over a drum track, then enters into a weird, unstructured bassy song with distorted lead guitar. Third track is a heavy track that alternates between heavy riffing and amazing guitar solos.",
/* 088 */	"The first 25 minutes consist of mind-bending experimental shred and riffage. Last track is a mellow and atmospheric guitar solo that will be remembered forever.",
/* 089 */	"Lots of hard rock riffing with layers of spacey sound bits on top. Ends with a bizarre ambience track.",
/* 090 */	"The first song is an extremely varied rock song with amazing lead guitar. The second and final track is a huge guitar solo with some great tapping sections.",

/* 091 */	"Funky riffs with clean, shreddy intermissions.",
/* 092 */	"Distorted riffing with much variety in an unstructured fashion.",
/* 093 */	"First track is slow-paced rock song with a beautiful lead. Second track is very funky and rhythmic. Final track is an atmospheric, emotional and mellow piece of art.",
/* 094 */	"Starts off with a heavy and consistent riff followed by a track with cool hybrid-picked sections. Next up are two rhythmic tracks that rely on riffs and the Pike then ends with a mellow track.",
/* 095 */	"Two huge guitar solos with the first one having a lot of killswitch goodness and the second one is simply non-stop soloing.",
/* 096 */	"Starts off with a crunchy, repetitive, but cool riff followed by insane shredding that will melt your face.",
/* 097 */	"Mellow Pike that builds up to a beautiful guitar solo.",
/* 098 */	"Unstructured Pike with heavily distorted bass, mostly steel guitar, and weird noises.",
/* 099 */	"Starts off with a long mellow and rocky jam followed by very rhythmic tracks.",
/* 100 */	"The first 20 minutes consists of funky, distorted riffing. The final track is a long and chill guitar jam.",

/* 101 */	"Starts off with a slow, mellow track with a clean sound. Then goes into a bluesy jam followed by an atmospheric and relaxing song.",
/* 102 */	"Largest part of the Pike is rhythmic and groovy riffing. Final track is more calm and jammy.",
/* 103 */	"Groovy riffs with an unusual lead that often goes chaotic.",
/* 104 */	"After a lengthy riff session this Pike will throw one solo after another to you.",
/* 105 */	"Starts off with a 10-minute track consisting of crunchy riffs, then goes into a huge and amazing guitar solo.",
/* 106 */	"Single track with percussion-driven riffs and lasers.",
/* 107 */	"Thirty minutes of amazing, non-stop shred to enjoy.",
/* 108 */	"Starts off with very heavy shredding, then slows down into a weird, distorted rock tune.",
/* 109 */	"Slow, relaxing jam session with echoey steel guitars.",
/* 110 */	"This Pike kicks off with a big shred fest. After that the baritone guitar introduces itself with delicious riffs and builds up to a fantastic guitar solo.",

/* 111 */	"Fast-paced varied hard rock track with amazing shred and solos. Final track is a riff fest with the occasional shred and growl.",
/* 112 */	"Non-stop chaotic shred with strange, bassy backing tracks.",
/* 113 */	"Unusual riffing and shredding followed by a 2 minutes of static noise. Third track continues the weird riffing and shredding. Final track is more structured and has pretty heavy riffs and shredding too.",
/* 114 */	"Slow, dark, and sludgy riffing.",
/* 115 */	"Sounds you didn't even know guitars could make. Bizarre screeching and static noise await.",
/* 116 */	"Starts off slow and relaxing, then a cool, distorted lead kicks up the pace. Ends with a atmospheric, mellow jam.",
/* 117 */	"This Pike only features bass and drums. The bass is deliciously rhythmic.",
/* 118 */	"Amazingly heavy riffs with cool guitar licks. Final track is an unpredictable rock track.",
/* 119 */	"The Pike begins with an upbeat song, then makes a sharp turn to an evil and heavy tone. Not long after that it'll be downtuned and very heavy.",
/* 120 */	"First track is quite unusual and has cool bass loops. After that the Pike goes into hard rock territory with quite the pace and weirdness. The final four tracks are more structured and catchy.",

/* 121 */	"Starts off with a very long, upbeat guitar jam that will put a smile on your face. Final two tracks are slightly heavier and have very cool and memorable riffs.",
/* 122 */	"First track is a long atmospheric and bluesy jam. Second track sounds a bit like classic rock with heavy emphasis on rhythm.",
/* 123 */	"Starts off with a fast-paced rock song with an awesome guitar solo. Second track features heavy and growly riffs with a catchy rhythm. Pike ends with an mysterious, Egyptian-like tune.",
/* 124 */	"Collection of very unpredictable progression, strange sounds and weird guitar.",
/* 125 */	"Hard rock riffing with solos and catchy melodies. Gets heavier towards the end.",
/* 126 */	"Starts off with a very atmospheric and chilling rock song. Rest of the Pike has some nice bassy backing tracks and rocky riffs. Final track goes heavy mode.",
/* 127 */	"A mix of rocking riffs and amazing guitar solos. Fourth track is a fast-paced steel guitar riff fest.",
/* 128 */	"Very atmospheric and relaxing songs played on a steel guitar that will put you to a dream-like state.",
/* 129 */	"Starts off mellow but doesn't take too long to switch it up to rocky riffs. Ends with a relaxing jam.",
/* 130 */	"A trip through the swamp with sludgy, downtuned riffs.",

/* 131 */	"Slow, distorted beauty with extremely atmospheric riffs.",
/* 132 */	"A collection of heavy, echoey riffs.",
/* 133 */	"Slow-paced, downtuned evilness rich in atmosphere and static noise.",
/* 134 */	"Steel guitar with lots of reverb and other strange background noises.",
/* 135 */	"Droney notes with creepy hums.",
/* 136 */	"Pure chaos, shred, and awesome riffs.",
/* 137 */	"First track kicks off with heavy riffs and shred. Second track gets even heavier and features kick-ass riffing.",
/* 138 */	"Brutally heavy with shred and weird, screechy riffs. Ends with a very cool guitar solo.",
/* 139 */	"Starts off with slow rocky riffs and builds up to a huge guitar solo.",
/* 140 */	"First track contains unpredictable sections with shred and strangely downtuned riffs. Second track is a long classic rock solo.",

/* 141 */	"Unstructured continuous track with slap bass and funky riffs.",
/* 142 */	"Percussion-driven Pike with cool riffs.",
/* 143 */	"Unusual riffing with occasional amazing guitar solos. Pike ends with a great, fast-paced guitar solo.",
/* 144 */	"Big shred fests ahead including a short, bassy jam.",
/* 145 */	"Non-stop bass action. Slow, fast, slap, and distorted.",
/* 146 */	"Buzzy unstructured Pike with steel guitar licks.",
/* 147 */	"Bass-driven riffs that heavily distort towards the end.",
/* 148 */	"Relaxing Pike with echoey, mellow jams.",
/* 149 */	"First track has an unforgettable guitar solo. The rest is a mix of rock, heavy, and generally weird riffs that never gets old.",
/* 150 */	"Two long and beautifully emotional guitar jams.",

/* 151 */	"First two tracks are dark riffs with interesting percussion. Final two tracks are rock-styled and ends with a nice solo.",
/* 152 */	"Lots of shred, growling, and killswitch action.",
/* 153 */	"Fast-paced rock with lots of shredding on top. Final two tracks are more structured and feature a cool solo.",
/* 154 */	"Starts off with a slow, mellow track that builds up to a faster and rockier pace. Final track gets very angry and features aggressive riffing.",
/* 155 */	"Atmospheric riffs with interesting distortion that get heavier throughout the Pike.",
/* 156 */	"Four tracks with each their own unique style. First one is a bassy jam, second one is heavy riffing, third one a mellow jam, and fourth one is slow, atmospheric riffage.",
/* 157 */	"This Pike features many different rock styles and melodies at different tempos.",
/* 158 */	"Aggressive riffing with clean interludes. Continues to be heavy all the way to the end.",
/* 159 */	"Starts off with distortion and lots of shred. Final track is a bizarre ambience track with very strange sound samples.",
/* 160 */	"Pike begins with a cool hard rock track that ends with a fantastic guitar solo. Second and third track are slightly heavier that climax with a short but powerful solo. Fourth track is a slow, atmospheric mellow track.",

/* 161 */	"Spooky pulsating beeps with a droney background hum.",
/* 162 */	"It begins with a slow and very atmospheric track. What follows next are a mix of hard rock and heavy tracks with unique-sounding riffs and sounds.",
/* 163 */	"Two long mellow guitar jams with echoey leads.",
/* 164 */	"A barrage of hard rock riffs that get even heavier in the second track.",
/* 165 */	"A bizzare jazzy jam with a very unpredictable theme. Final track is a strange ambient track that is oddly eerie.",
/* 166 */	"Five tasty guitar solos with great bassy backing tracks.",
/* 167 */	"Massive and unforgettable guitar solo in the first track. Second track relies on heavy riffs while the third one calms down with a mellow song.",
/* 168 */	"Strange downtuned riffage with crazy shreddy licks.",
/* 169 */	"Fantastic bass jam that ends with a unique-sounding guitar solo.",
/* 170 */	"A long, slow mellow jam with a clean sound and varied melodies. Second track does a 180 and relies on heavy riffs.",

/* 171 */	"Strangely satisfying heavy riffs with lasers and killswitch action.",
/* 172 */	"Extremely heavy riffing that will make you headbang without a doubt.",
/* 173 */	"Aggressive-sounding Pike with brutal riffs, lasers, killswitch action, and tons of shred.",
/* 174 */	"Fast-paced riffing with an unreal amount of shredding.",
/* 175 */	"A relaxing synth background hum with steel guitar pluckings that will help you sleep.",
/* 176 */	"Very slow and random guitar picking playing spooky notes.",
/* 177 */	"Steel guitar with eerie ambient sounds.",
/* 178 */	"Beginning builds up to heavy, unstructured riffing followed by fantastic guitar licks and shred.",
/* 179 */	"Lasers, saws and robotic noises.",
/* 180 */	"Lasers, low resonance and guitar pluckings.",

/* 181 */	"Pulsating ambience, airhorns and strange animal-like sounds.",
/* 182 */	"Disembodied pan flutes, distorted synths, digging noises and more random sound clips from various objects.",
/* 183 */	"Spooky high-pitched noises with reverb.",
/* 184 */	"Ominous windy sounds with sporadic guitar pluckings.",
/* 185 */	"Violent screeches with slow steel guitar sections inbetween.",
/* 186 */	"Random guitar strumming with reverb.",
/* 187 */	"Crazy synths and other electronic stuff.",
/* 188 */	"Synths and other bizarre sound effects including a xylophone rampage.",
/* 189 */	"Starts off with rhythmic synth, then goes full spook mode with creepy electronic noises.",
/* 190 */	"Low pitched, hard-hitting pulses.",

/* 191 */	"Slow notes and lots of reverb.",
/* 192 */	"Atmospheric screeching with reverb.",
/* 193 */	"Bizarre distorted and buzzy synth.",
/* 194 */	"Slow, steel guitar noodling.",
/* 195 */	"Droney with interesting electronic sounds and samples.",
/* 196 */	"Random guitar plucking with lots of reverb and the occassional screech.",
/* 197 */	"Horror soundtrack from space. Lots of beeps, boops and otherworldy machinery.",
/* 198 */	"A bunch of swirly noises and low-pitched hums.",
/* 199 */	"Starts off with heavy percussion-driven screechy riffs, then removes the drums but continues the screeching at a much slower pace.",
/* 200 */	"Banjo accompanied by synths.",

/* 201 */	"Strange and creepy noises you'd hear inside a flying saucer.",
/* 202 */	"Very droney with synths and what sounds like a tiny piano.",
/* 203 */	"Crunchy. As if thousands of papers were torn, crumpled and crushed during the recording.",
/* 204 */	"Steel guitar with low, ominous pulses in the background.",
/* 205 */	"Spine-chilling synths with reverb.",
/* 206 */	"A lot of random tapping noises and strumming.",
/* 207 */	"Synths accompanied by a spooky background hum.",
/* 208 */	"Relaxing, atmospheric steel guitar plucking and chords with reverb.",
/* 209 */	"Slow, mellow continuous track containing steel guitar that builds up to a big guitar jam.",
/* 210 */	"Fast-paced hard rock with incredible shredding and long, extended guitar solo. The Pike ends with very heavy, amazing shredding.",

/* 211 */	"Six hard rock tracks high in variety. Guitar solos sound emotional in this one.",
/* 212 */	"This Pike begins with a very long and beautiful atmospheric track. The next track is a 10-minute long guitar solo that will blow your mind.",
/* 213 */	"It's 29 minutes of non-stop, God tier soloing and shredding. Enough said.",
/* 214 */	"Slow-paced, echoey, atmospheric Pike consisting of steel guitar notes and chords.",
/* 215 */	"The intro song is an amazing 7-minute guitar solo. It then sets a heavier tone with crazy shredding sections.",
/* 216 */	"Seven rock tracks with much variety in tone and melodies.",
/* 217 */	"Starts off with a long, relaxing, atmospheric mellow jam. The second track kicks up the pace and will blow your mind with an amazing guitar solo performance.",
/* 218 */	"Mix of rock and mellow backing tracks with fantastic solos played on top.",
/* 219 */	"First half consists of mellow tunes, then does a complete 180 and goes full heavy mode including growls and shred.",
/* 220 */	"A beautiful acoustic backing track and solo welcomes you for the first half of the Pike. Suddenly goes very heavy and shreddy along with interesting sound bits",

/* 221 */	"Long mellow jam with an acoustic backing track and great clean lead guitar.",
/* 222 */	"This one will get you headbanging. Downtuned riffing and occasional shredding.",
/* 223 */	"Repetitive but serene backing track consisting of slow acoustic chords with a calm lead on top.",
/* 224 */	"Varied Pike that never plays the same section twice. Very atmospheric.",
/* 225 */	"A single track of hard rock with a consistent theme and memorable riffs.",
/* 226 */	"Starts off with a 10-minute guitar solo with face-melting shred followed by a riff-fest. If that wasn't enough, a second guitar jam will be ready to blow your mind afterwards.",
/* 227 */	"Begins with a slow, echoey mellow track. The second track kicks it up a notch and consists of heavy, aggressive riffing. Third track calms down into a long, atmospheric mellow jam.",
/* 228 */	"Non-stop heavy riffing with shreddy breaks inbetween.",
/* 229 */	"Begins with a short, melodic song followed by some downtuned riffing. The highlight is the final track which is a very atmospheric jam with an echoey, downtuned backing track.",
/* 230 */	"First track is a huge guitar solo with many great moments. Second track is strange, heavy riffing with clean, echoey breaks inbetween.",

/* 231 */	"Starts off with a slow, atmospheric piece. Second track is an upbeat rock song. The third track plays slow, heavy, atmospheric notes. Final track is a fast-paced rock song that alternates between riffs and shred.",
/* 232 */	"You're met with a growling for the first 7 or so minutes, then throws you into a pit with a beast of a guitar solo. Rest of the Pike follows the same pattern, but with less growling and shorter solos.",
/* 233 */	"First half is a fast-paced hard rock that builds up to a long guitar solo. Second track is a lengthy song that alternates between growling, shredding, and guitar solos.",
/* 234 */	"You're greeted with an atmospheric and heavy song with shreddy moments. The title track is a 15-minute echoey guitar jam that will mesmerise you.",
/* 235 */	"Rocky riffs that build up towards a guitar solo.",
/* 236 */	"Fairly heavy Pike with no direction whatsoever. Deliciously unpredictable. Final track is a creepy, atmospheric song with lots of reverb.",
/* 237 */	"Chill continuous track with a consistent theme and reocurring hybrid-picked melodies.",
/* 238 */	"Creepy, heavy riffs with shreddy moments and beautifully atmospheric breaks.",
/* 239 */	"Starts off with a mellow guitar jam followed by three, rhytmic rock solos.",
/* 240 */	"First track is lots of aggressive riffing. Rest of the Pike is less heavy, but the final track sure sounds evil.",

/* 241 */	"Wonderful collection of both slow and fast steel guitar action. Exceptionally high production value.",
/* 242 */	"Non-stop heavy shredding and tapping.",
/* 243 */	"First two tracks are fairly heavy with many unusual sound samples. Third track is a steel guitar piece of art with a Western theme. The rest of the Pike follows the same pattern as the first two tracks.",
/* 244 */	"First track is a short, unstructured riff fest. Second track is a chill, melodic rock song. The third track is a slow, heavy, and unstructured experimental track. The Pike then ends with a short but cool guitar solo.",
/* 245 */	"Starts off with a 21-minute long mellow and emotional guitar solo. Up next is a short acoustic song followed by a pretty shreddy guitar solo.",
/* 246 */	"Most songs in this Pike are heavy riffs except for the second track which is a very calm and emotional song. Another exception is track 4 and 5, which is basically a single song which builds up to a fantastic guitar solo.",
/* 247 */	"Beautiful, atmospheric and varied steel guitar jamming with an occasional electric guitar lead.",
/* 248 */	"This Pike has a very dreamy tone and consists of many different melodies and moods.",
/* 249 */	"Pike with a classic rock sound and many riffs. Has the occasional guitar lick and shred to pump things up.",
/* 250 */	"Lots of heavy riffing and growling. Towards the second half of the Pike the bass guitar makes an appearance and won't disappoint.",

/* 251 */	"Majority of this Pike consists of beautiful steel guitar melodies and jams. Ends with more steel guitar and growly interludes.",
/* 252 */	"Starts off with a cool, atmospheric track with a great tapping solo towards the end. The rest of the Pike consists of rocky tunes, classical guitar, and heavy riffs.",
/* 253 */	"Melodic shred until the final track, which is a beautifully chill guitar solo.",
/* 254 */	"Unstructured continuous track with heavy riffs and eerie steel guitar breaks.",
/* 255 */	"Hard rock riffing with shreddy interludes.",
/* 256 */	"First half of the Pike consists of slow, but chunky riffs and amazing guitar solos. The second half is a lot heavier and shreddier with sporadic, steel guitar breaks.",
/* 257 */	"Collection of beautiful, rocky jams. Tempo varies from slow to fast.",
/* 258 */	"Soothing and relaxing Pike with long, mellow guitar jams. Final track is slightly more rock oriented.",
/* 259 */	"Brutally heavy riffs with the occassional shred. Second track features a calm and unusual outro. Fifth track is a short, calm and relaxing jam.",
/* 260 */	"Energised riffing with eerie interludes.",

/* 261 */	"First half contains a lot of heavy riffage. Second half starts of mellow, then builds up to a guitar riffs and solos that will pump you up.",
/* 262 */	"A constant barrage of fast riffs and shred.",
/* 263 */	"Starts off with a 13-minute guitar solo. Up next is a Western-style guitar piece followed by heavy riffs and chill sections.",
/* 264 */	"A continuous hard rock track with exceptional riffs and solos. Very varied and melodic.",
/* 265 */	"Unpredictable Pike that will kick your ass with very heavy, unusual riffs and shred. Final track is more structured and hard rock oriented.",
/* 266 */	"Calm continuous track that builds up to a slow and beautiful guitar solo.",
/* 267 */	"Chaotic and brutal riffage with growls and crazy shred. Ends with a calm ambience track.",
/* 268 */	"Slowly builds up to a big, hard rock guitar solo followed by a ridiculously heavy track and shred. Ends with very cool riffing.",
/* 269 */	"Melodic mix of hard rock songs and the occasional heavy riffing. Final track is multiple layers of crazy shred with the strangest panning you've ever heard.",
/* 270 */	"Hauntingly beautiful steel guitar plucking and tremolo strumming with reverb.",

/* 271 */	"First track is a guitar solo with a classic rock theme. Rest of the Pike is a mix of hard rock riffs and solos.",
/* 272 */	"Single track consisting only of calming strings with reverb.",
/* 273 */	"Unstructured Pike with various tunes including but not limited to riffing, growling, screeching, and glitchy shredding.",
/* 274 */	"Fast-paced hard rock track with cool interludes and solos. Second track is growly, heavier, shreddy, and more experimental.",
/* 275 */	"Starts off with a slow, mellow atmospheric track. After that it just goes nuts with shred, heavy riffs, calm interludes, and unusual sound bits.",
]